DROP TABLE IF EXISTS TBD;
CREATE TABLE TBD (
  post_id CHAR(6) PRIMARY KEY,
  date DATE NOT NULL,
  lngID INTEGER REFERENCES lng(ID),
  contID INTEGER REFERENCES cont(ID),
  time CHAR(2) NOT NULL
);

DROP TABLE IF EXISTS LNG;
CREATE TABLE LNG (
  lngID INTEGER NOT NULL,
  lng CHAR(20) UNIQUE
);

DROP TABLE IF EXISTS CONT;
CREATE TABLE CONT (
  contID INTEGER NOT NULL,
  cont CHAR(20) UNIQUE
);